version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - "9901:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus/data'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    restart: always

volumes:
  grafana_data:
  prometheus_data:
